### ISSUE TITLE
Handlebars doesn't work on Rust 1.69.0: pattern `pest_meta::optimizer::OptimizedExpr::NodeTag(_, _)` not covered

### ISSUE THREAD

**Issue by mdennyh** [sunng87/handlebars-rust#583]
Rustc version: `rustc 1.69.0 (84c898d65 2023-04-16)`
Handlebars version: "4.3.7"

```
error[E0004]: non-exhaustive patterns: `pest_meta::optimizer::OptimizedExpr::NodeTag(_, _)` not covered
   --> C:\Users\mdenn\.cargo\registry\src\github.com-1ecc6299db9ec823\pest_generator-2.5.6\src\generator.rs:524:11
    |
524 |     match expr {
    |           ^^^^ pattern `pest_meta::optimizer::OptimizedExpr::NodeTag(_, _)` not covered
    |
note: `pest_meta::optimizer::OptimizedExpr` defined here
   --> C:\Users\mdenn\.cargo\registry\src\github.com-1ecc6299db9ec823\pest_meta-2.6.0\src\optimizer\mod.rs:142:5
    |
114 | pub enum OptimizedExpr {
    | ----------------------
...
142 |     NodeTag(Box<OptimizedExpr>, String),
    |     ^^^^^^^ not covered
    = note: the matched value is of type `pest_meta::optimizer::OptimizedExpr`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
651 ~         }
652 +         pest_meta::optimizer::OptimizedExpr::NodeTag(_, _) => todo!()
```

Just try to install it and it just doesn't work anymore. I'll try to downgrade Rust

**Comment by mdennyh** [comment]
I'm sorry it seems the issue went away after I install the beta version of handlebars ("5.0.0-beta.2")
